document.getElementById("dinatos_dimos_pososto").innerHTML 	 = String(dynatos['synoliko'])+'%';
document.getElementById("nisi_pososto").innerHTML       	 = String(nisi['synoliko'])+'%';
document.getElementById("konta_dimoti_pososto").innerHTML 	 = String(konta['synoliko'])+'%';
document.getElementById("prwtoboulia_pososto").innerHTML 	 = String(protovoulia['synoliko'])+'%';
document.getElementById("anasygkrotisi_pososto").innerHTML 	 = String(anasygkrotisi['synoliko'])+'%';
document.getElementById("vima_pososto").innerHTML 			 = String(vima['synoliko'])+'%';
document.getElementById("laiki_pososto").innerHTML 			 = String(laiki['synoliko'])+'%';
document.getElementById("date_time").innerHTML 			     = "Τελευταία Ενημέρωση: Κυριακή 26.05.2019, " + date_time ;
document.getElementById("enswmatwsi").innerHTML 			 = "Ενσωμάτωση: " + enswmatwsi + "%";